// Mock registrations data
export const mockRegistrations = [
    {
        id: 1,
        name: "Arun Sharma",
        email: "arun.sharma@gmail.com",
        phone: "9876543210",
        school: "JNV Kannur",
        registrationType: "Premium",
        amount: "₹1000",
        paymentStatus: "Paid",
        registrationDate: "2023-12-15",
    },
    {
        id: 2,
        name: "Priya Patel",
        email: "priya.patel@gmail.com",
        phone: "8765432109",
        school: "JNV Ernakulam",
        registrationType: "Premium",
        amount: "₹1000",
        paymentStatus: "Paid",
        registrationDate: "2023-12-14",
    },
    {
        id: 3,
        name: "Mohammed Ali",
        email: "mohammed.ali@outlook.com",
        phone: "7654321098",
        school: "JNV Kozhikode",
        registrationType: "Standard",
        amount: "₹500",
        paymentStatus: "Paid",
        registrationDate: "2023-12-12",
    },
    {
        id: 4,
        name: "Lakshmi Nair",
        email: "lakshmi.nair@yahoo.com",
        phone: "6543210987",
        school: "JNV Thiruvananthapuram",
        registrationType: "Standard",
        amount: "₹500",
        paymentStatus: "Pending",
        registrationDate: "2023-12-10",
    },
    {
        id: 5,
        name: "John Thomas",
        email: "john.thomas@gmail.com",
        phone: "9876543211",
        school: "JNV Idukki",
        registrationType: "Supporter",
        amount: "₹2000",
        paymentStatus: "Paid",
        registrationDate: "2023-12-09",
    },
    {
        id: 6,
        name: "Anjali Menon",
        email: "anjali.menon@outlook.com",
        phone: "9876543212",
        school: "JNV Wayanad",
        registrationType: "Standard",
        amount: "₹500",
        paymentStatus: "Pending",
        registrationDate: "2023-12-08",
    },
    {
        id: 7,
        name: "Rajesh Kumar",
        email: "rajesh.kumar@gmail.com",
        phone: "9876543213",
        school: "JNV Kollam",
        registrationType: "Premium",
        amount: "₹1000",
        paymentStatus: "Paid",
        registrationDate: "2023-12-07",
    },
    {
        id: 8,
        name: "Sameera Khan",
        email: "sameera.khan@yahoo.com",
        phone: "9876543214",
        school: "JNV Kasaragod",
        registrationType: "Standard",
        amount: "₹500",
        paymentStatus: "Paid",
        registrationDate: "2023-12-06",
    },
    {
        id: 9,
        name: "Thomas Jacob",
        email: "thomas.jacob@gmail.com",
        phone: "9876543215",
        school: "JNV Pathanamthitta",
        registrationType: "Supporter",
        amount: "₹2000",
        paymentStatus: "Pending",
        registrationDate: "2023-12-05",
    },
    {
        id: 10,
        name: "Sara Ali",
        email: "sara.ali@outlook.com",
        phone: "9876543216",
        school: "JNV Kottayam",
        registrationType: "Standard",
        amount: "₹500",
        paymentStatus: "Paid",
        registrationDate: "2023-12-04",
    },
    {
        id: 11,
        name: "Varun Menon",
        email: "varun.menon@gmail.com",
        phone: "9876543217",
        school: "JNV Alappuzha",
        registrationType: "Premium",
        amount: "₹1000",
        paymentStatus: "Paid",
        registrationDate: "2023-12-03",
    },
    {
        id: 12,
        name: "Meera Rajesh",
        email: "meera.rajesh@yahoo.com",
        phone: "9876543218",
        school: "JNV Malappuram",
        registrationType: "Standard",
        amount: "₹500",
        paymentStatus: "Pending",
        registrationDate: "2023-12-02",
    },
];

// Mock dashboard stats
export const mockDashboardStats = {
    totalRegistrations: 142,
    newRegistrations: 23,
    totalRevenue: 98500,
    newRevenue: 15500,
    pendingPayments: 18,
    pendingAmount: 12500,
    conversionRate: 78,
    conversionTrend: 5.2,

    // This would be used in a real app with proper charting
    registrationTrends: [
        { date: '2023-11-01', count: 5 },
        { date: '2023-11-02', count: 7 },
        { date: '2023-11-03', count: 8 },
        { date: '2023-11-04', count: 12 },
        { date: '2023-11-05', count: 15 },
        { date: '2023-11-06', count: 18 },
        { date: '2023-11-07', count: 14 },
        { date: '2023-11-08', count: 9 },
        { date: '2023-11-09', count: 11 },
        { date: '2023-11-10', count: 13 },
    ],

    // School distribution
    schoolDistribution: [
        { school: 'JNV Kannur', count: 18 },
        { school: 'JNV Ernakulam', count: 22 },
        { school: 'JNV Kozhikode', count: 15 },
        { school: 'JNV Thiruvananthapuram', count: 24 },
        { school: 'JNV Idukki', count: 12 },
    ],

    // Registration type distribution
    registrationTypeDistribution: [
        { type: 'Standard', count: 78 },
        { type: 'Premium', count: 48 },
        { type: 'Supporter', count: 16 },
    ]
};

// Mock admin settings
export const mockAdminSettings = {
    eventName: 'UNMA 2025 Reunion',
    eventDate: '2025-03-15',
    eventLocation: 'JNV Kannur, Kerala, India',
    registrationFee: {
        standard: 500,
        premium: 1000,
        supporter: 2000
    },
    emailNotifications: true,
    allowRegistrations: true,
    maxRegistrations: 300,
    paymentGateway: 'razorpay',
    logoUrl: 'https://example.com/logo.png',
    socialLinks: {
        facebook: 'https://facebook.com/unma2025',
        twitter: 'https://twitter.com/unma2025',
        instagram: 'https://instagram.com/unma2025'
    }
}; 